# Generated by Django 5.2.16 on 2026-07-22 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('dossier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('en_retard', 'En retard')], db_index=True, default='brouillon', max_length=20)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='factures', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='dossier.dossier')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factures',
            },
        ),
    ]
