# Generated by Django 5.2.16 on 2026-07-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_alter_facture_montant_ht_alter_facture_montant_ttc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
