# Generated by Django 5.2.16 on 2026-07-22 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('personne_physique', 'Personne Physique'), ('personne_morale', 'Personne Morale')], db_index=True, default='personne_physique', max_length=20)),
                ('nom', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('raison_sociale', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ifu_rccm', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone1', models.CharField(max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'indexes': [models.Index(fields=['nom', 'prenom'], name='clients_nom_a4c76b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('nom__isnull', False), ('type', 'personne_physique')), models.Q(('raison_sociale__isnull', False), ('type', 'personne_morale')), _connector='OR'), name='client_nom_ou_raison_sociale_requis')],
            },
        ),
    ]
