# Generated by Django 5.2.16 on 2026-07-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nom_complet',
        ),
        migrations.RemoveField(
            model_name='client',
            name='siret',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone1',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='telephone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
