# Generated by Django 5.2.16 on 2026-07-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_nom_complet_remove_client_siret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ifu_rccm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
