# Generated by Django 5.2.16 on 2026-07-20 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_ifu_rccm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nom__isnull', False), ('type', 'personne_physique')), models.Q(('raison_sociale__isnull', False), ('type', 'personne_morale')), _connector='OR'), name='client_nom_ou_raison_sociale_requis'),
        ),
    ]
