# Generated by Django 5.2.16 on 2026-07-18 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('intitule', models.CharField(max_length=255)),
                ('type_affaire', models.CharField(choices=[('civil', 'Civil'), ('penal', 'Pénal'), ('commercial', 'Commercial'), ('social', 'Social'), ('famille', 'Famille'), ('administratif', 'Administratif'), ('autre', 'Autre')], db_index=True, default='autre', max_length=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('plaide', 'Plaidé'), ('clos', 'Clos'), ('archive', 'Archivé')], db_index=True, default='ouvert', max_length=20)),
                ('juridiction', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_prochaine_echeance', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avocat_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_referes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dossiers', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dossiers',
            },
        ),
    ]
