# Generated by Django 5.2.16 on 2026-07-22 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_ajout_fk_tribunal'),
        ('dossier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='tribunal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='authentication.tribunal'),
        ),
    ]
