# Generated by Django 5.2.16 on 2026-07-22 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_ajout_fk_tribunal'),
        ('dossier', '0002_ajout_fk_tribunal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='degre_instance',
            field=models.CharField(choices=[('premiere_instance', 'Première instance'), ('appel', 'Appel'), ('cassation', 'Cassation')], default='premiere_instance', max_length=20),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dossier_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_recours', to='dossier.dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='juge_en_charge',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='numero_bureau',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='numero_role',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='partie_adverse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='authentication.tribunal')),
            ],
            options={
                'unique_together': {('tribunal', 'libelle')},
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dossier.chambre'),
        ),
    ]
