# Generated by Django 5.2.16 on 2026-07-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_chambre'),
        ('dossier', '0003_dossier_degre_instance_dossier_dossier_origine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.chambre'),
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
    ]
