# Generated by Django 5.2.16 on 2026-07-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_chambre_options_chambre_notes_and_more'),
        ('dossier', '0004_alter_dossier_chambre_delete_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='juridiction',
        ),
        migrations.AddField(
            model_name='dossier',
            name='avocat_adverse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='authentication.chambre'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='numero_role',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro de rôle/RG attribué par le greffe', max_length=50, null=True),
        ),
    ]
