# Generated by Django 5.2.16 on 2026-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0005_remove_dossier_juridiction_dossier_avocat_adverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='juridiction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
