# Generated by Django 5.2.16 on 2026-07-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0006_dossier_juridiction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='juridiction',
        ),
    ]
