# Generated by Django 5.2.16 on 2026-08-01 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0007_remove_dossier_juridiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex: Chambre de Conseil, Correctionnelle, ECOFI', max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'db_table': 'chambres',
                'ordering': ['tribunal', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: Tribunal Judiciaire de Paris', max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Ex: T.G.I.O — abréviation utilisée dans les documents/courriers', max_length=20, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('ville', models.CharField(db_index=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_greffe', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunaux',
                'db_table': 'tribunal',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeTribunal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Ex: 'TJ', 'TC', 'CA'", max_length=15, unique=True)),
                ('libelle', models.CharField(help_text="Ex: 'Tribunal Judiciaire'", max_length=150)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text='Ordre dans les menus déroulants')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de Tribunal',
                'verbose_name_plural': 'Types de Tribunaux',
                'db_table': 'type_tribunal',
                'ordering': ['ordre_affichage', 'libelle'],
            },
        ),
        migrations.AlterField(
            model_name='dossier',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='dossier.chambre'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='dossier.tribunal'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='tribunal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='dossier.tribunal'),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='type_tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tribunaux', to='dossier.typetribunal'),
        ),
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together={('tribunal', 'libelle')},
        ),
    ]
