# Generated by Django 5.2.16 on 2026-07-29 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, max_length=20)),
                ('capacite', models.CharField(db_index=True, max_length=50)),
                ('autorise', models.BooleanField(help_text="Coché = accorde l'accès. Décoché = retire l'accès, même si accordé par défaut.")),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surcharge de permission (par rôle)',
                'db_table': 'permissions_roles',
                'unique_together': {('role', 'capacite')},
            },
        ),
    ]
