"""
Django settings for ecabinet project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, str(BASE_DIR / 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!1tvo520x&5iry84oo118si@4-fi9q$r9%%0+mtukmq3l#x9ql'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
TAILWIND_APP_NAME = 'theme'

NPM_BIN_PATH = r"C:/Program Files/nodejs/npm.cmd" # Chemin vers le binaire npm sur Windows


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

# Librairies tierces indispensables
    'rest_framework',

    'apps.authentication',
    'apps.client',
    'apps.dossier',
    'apps.documents',
    'apps.agenda',
    'apps.facturation',
    'apps.portal',
    'apps.dashboard',
    'apps.notifications',
    'apps.statistiques',
    
    'apps.core',


    'tailwind',
    'theme',  # C'est le nom de l'application contenant Tailwind que nous allons créer
    'django_browser_reload',  # Facultatif (rechargement automatique)

    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.core.middleware.LoginRequiredMiddleware',               # <- ajouté juste après
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "django_browser_reload.middleware.BrowserReloadMiddleware", # Facultatif (rechargement automatique)
]

#ROOT_URLCONF = 'ecabinet.urls'
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'apps.core.context_processors.permissions_utilisateur',   # <- ajouté
            ],
        },
    },
]

#WSGI_APPLICATION = 'ecabinet.wsgi.application'
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_ecabinet3',
        'USER': 'root',
        'PASSWORD': 'Adm!n!StraTeur123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'CONN_MAX_AGE': 60,   # réutilise la connexion MySQL au lieu d'en rouvrir une à chaque requête
    }
}

# Configuration Celery (Utilisation de Redis en local)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Ouagadougou'  # Fuseau horaire du Burkina Faso


#AUTH_USER_MODEL = 'apps.authentication.User'
AUTH_USER_MODEL = 'authentication.User'

SESSION_COOKIE_SECURE = True       # cookie de session jamais envoyé en HTTP clair
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True     # inaccessible en JS (protection XSS sur le cookie)
SESSION_COOKIE_AGE = 3600 * 8      # 8h — cohérent avec une journée de travail cabinet
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
LOGIN_URL = 'authentication:connexion'
LOGIN_REDIRECT_URL = 'dashboard:liste'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    #{'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# settings.py
AUTHENTICATION_BACKENDS = [
    'authentication.backends.CabinetAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # conservé en secours (admin Django, etc.)
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Forcer le format d'affichage
USE_L10N = False 
DATETIME_FORMAT = 'd/m/Y a H:i:s'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# CORRECTION DU CHEMIN : On s'assure de cibler la vraie racine du projet
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Ajoutez également cette ligne si elle est absente (indispensable pour la production et le cache)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
