# Generated by Django 5.2.16 on 2026-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementagenda',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
