# Generated by Django 5.2.16 on 2026-07-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('dossier', '0002_ajout_fk_tribunal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementagenda',
            name='type',
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='date_declencheur',
            field=models.DateField(blank=True, help_text='Ex: date de signification du jugement', null=True),
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='duree_legale_jours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='statut_traitement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité dans les délais'), ('forclos', 'Forclos / délai dépassé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='type_delai',
            field=models.CharField(blank=True, choices=[('appel', 'Appel'), ('pourvoi', 'Pourvoi en cassation'), ('opposition', 'Opposition'), ('tierce_opposition', 'Tierce opposition'), ('execution', "Délai d'exécution"), ('autre', 'Autre délai')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='dossier.dossier'),
        ),
    ]
