# Generated by Django 5.2.16 on 2026-07-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_evenementagenda_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementagenda',
            name='type',
            field=models.CharField(choices=[('audience', 'Audience'), ('rdv_client', 'Rendez-vous Client'), ('delai_procedure', 'Délai Procédure'), ('autre', 'Autre')], db_index=True, default='autre', max_length=20),
        ),
    ]
