# Generated by Django 5.2.16 on 2026-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_evenementagenda_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementagenda',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
