# Generated by Django 5.2.16 on 2026-07-23 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_evenementagenda_description'),
        ('dossier', '0006_dossier_juridiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiePrenante',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('client', 'Client'), ('avocat_referent', 'Avocat référent'), ('avocat_adverse', 'Avocat adverse'), ('temoin', 'Témoin'), ('huissier', 'Huissier'), ('expert', 'Expert judiciaire'), ('autre', 'Autre')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notifiable', models.BooleanField(default=True, help_text="Reçoit les rappels d'agenda de ce dossier")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_prenantes', to='dossier.dossier')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parties_prenantes',
            },
        ),
    ]
