# Generated by Django 5.2.16 on 2026-07-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_partieprenante'),
    ]

    operations = [
        migrations.AddField(
            model_name='partieprenante',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
