# Generated by Django 5.2.16 on 2026-07-23 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_partieprenante_notes'),
        ('authentication', '0007_alter_chambre_options_chambre_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenementagenda',
            options={'ordering': ['date_heure']},
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text="Avocats ou collaborateurs responsables d'assurer l'événement", related_name='evenements_agenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.chambre'),
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='date_echeance_calculee',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date limite légale recalculée', null=True),
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='tribunal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.tribunal'),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='statut_traitement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité dans les délais'), ('renvoye', 'Renvoyé à une autre date'), ('forclos', 'Forclos / délai dépassé'), ('autre', 'Autre')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='type',
            field=models.CharField(choices=[('audience', 'Audience'), ('rdv_client', 'Rendez-vous Client'), ('delai_procedure', 'Délai Procédure'), ('delibere', 'Prompt / Délibéré'), ('demarche_externe', 'Démarche Greffe / Huissier'), ('autre', 'Autre')], db_index=True, default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='type_delai',
            field=models.CharField(blank=True, choices=[('appel', 'Appel'), ('pourvoi', 'Pourvoi en cassation'), ('opposition', 'Opposition'), ('tierce_opposition', 'Tierce opposition'), ('execution', "Délai d'exécution"), ('memoire', 'Dépôt de mémoire / Conclusions'), ('autre', 'Autre délai')], max_length=25, null=True),
        ),
    ]
