# Generated by Django 5.2.16 on 2026-07-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_evenementagenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementagenda',
            name='parties_prenantes',
            field=models.ManyToManyField(blank=True, help_text='Parties prenantes associées à cet événement', related_name='evenements', to='agenda.partieprenante'),
        ),
    ]
