# Generated by Django 5.2.16 on 2026-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_evenementagenda_parties_prenantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementagenda',
            name='motif_renvoi',
            field=models.CharField(blank=True, choices=[('comm_pieces', 'Pour communication de pièces'), ('replique', 'Pour réplique / conclusions'), ('plaidoirie', 'Pour plaidoiries'), ('composition', 'Composition de la juridiction'), ('consignation', 'Paiement de consignation'), ('autre', 'Autre motif')], max_length=20, null=True),
        ),
    ]
