# Generated by Django 5.2.16 on 2026-07-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_evenementagenda_motif_renvoi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenementagenda',
            old_name='assigned_to',
            new_name='responsables',
        ),
    ]
