# Generated by Django 5.2.16 on 2026-07-24 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_rename_assigned_to_evenementagenda_responsables'),
        ('dossier', '0007_remove_dossier_juridiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partieprenante',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_prenantes', to='dossier.dossier'),
        ),
    ]
