# Generated by Django 5.2.16 on 2026-08-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_partieprenante_dossier'),
        ('dossier', '0008_chambre_tribunal_typetribunal_alter_dossier_chambre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementagenda',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dossier.chambre'),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='tribunal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dossier.tribunal'),
        ),
    ]
