# Generated by Django 5.2.16 on 2026-07-22 00:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(db_index=True, max_length=150, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTribunal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Ex: 'TJ', 'TC', 'CA'", max_length=15, unique=True)),
                ('libelle', models.CharField(help_text="Ex: 'Tribunal Judiciaire'", max_length=150)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text='Ordre dans les menus déroulants')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de Tribunal',
                'verbose_name_plural': 'Types de Tribunaux',
                'ordering': ['ordre_affichage', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('associe', 'Associé'), ('avocat', 'Avocat'), ('collaborateur', 'Collaborateur'), ('secretariat', 'Secrétariat'), ('stagiaire', 'Stagiaire'), ('comptable', 'Comptable')], db_index=True, default='collaborateur', max_length=20)),
                ('numero_toque', models.CharField(blank=True, help_text='Numéro de case au Tribunal', max_length=50, null=True)),
                ('case_barreau', models.CharField(blank=True, help_text='Ex: Barreau de Paris', max_length=100, null=True)),
                ('departement', models.CharField(blank=True, help_text='Ex: Pôle Pénal, Droit Social', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('telephone_direct', models.CharField(blank=True, max_length=20, null=True)),
                ('taux_horaire_defaut', models.DecimalField(blank=True, decimal_places=2, help_text='Taux horaire standard HT appliqué pour cet utilisateur', max_digits=10, null=True)),
                ('date_prestation_serment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('specialites', models.ManyToManyField(blank=True, related_name='utilisateurs', to='authentication.specialite')),
            ],
            options={
                'verbose_name': 'Utilisateur / Collaborateur',
                'verbose_name_plural': 'Utilisateurs / Collaborateurs',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: Tribunal Judiciaire de Paris', max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('ville', models.CharField(db_index=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_greffe', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type_tribunal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tribunaux', to='authentication.typetribunal')),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunaux',
                'ordering': ['ville', 'nom'],
            },
        ),
    ]
