# Generated by Django 5.2.16 on 2026-07-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialite',
            options={'verbose_name': 'Spécialité', 'verbose_name_plural': 'Spécialités'},
        ),
        migrations.AlterModelTable(
            name='specialite',
            table='specialite',
        ),
        migrations.AlterModelTable(
            name='tribunal',
            table='tribunal',
        ),
        migrations.AlterModelTable(
            name='typetribunal',
            table='type_tribunal',
        ),
    ]
