# Generated by Django 5.2.16 on 2026-07-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_specialite_options_alter_specialite_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='case_barreau',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numero_toque',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
