# Generated by Django 5.2.16 on 2026-07-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_case_barreau_remove_user_numero_toque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
    ]
