# Generated by Django 5.2.16 on 2026-07-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_nom_remove_user_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Ex: T.G.I.O — abréviation utilisée dans les documents/courriers', max_length=20, null=True, unique=True),
        ),
    ]
