# Generated by Django 5.2.16 on 2026-07-22 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_ajout_fk_tribunal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='authentication.tribunal')),
            ],
            options={
                'unique_together': {('tribunal', 'libelle')},
            },
        ),
    ]
