# Generated by Django 5.2.16 on 2026-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_chambre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'ordering': ['tribunal', 'libelle'], 'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
        migrations.AddField(
            model_name='chambre',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='libelle',
            field=models.CharField(help_text='Ex: Chambre de Conseil, Correctionnelle, ECOFI', max_length=150),
        ),
        migrations.AlterModelTable(
            name='chambre',
            table='chambres',
        ),
    ]
