# Generated by Django 5.2.16 on 2026-07-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_chambre_options_chambre_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
