# Generated by Django 5.2.16 on 2026-07-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_telephone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_dernier_changement_mdp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='derniere_connexion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False, help_text='Force le changement au prochain login (compte créé par un admin, mot de passe temporaire).'),
        ),
        migrations.AddField(
            model_name='user',
            name='tentatives_echouees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verrouille_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
