# Generated by Django 5.2.16 on 2026-07-25 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_date_dernier_changement_mdp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_saisi', models.EmailField(help_text="Conservé même si l'utilisateur n'existe pas, pour détecter les tentatives suspectes", max_length=254)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('succes', models.BooleanField()),
                ('date_tentative', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_connexions',
                'ordering': ['-date_tentative'],
            },
        ),
    ]
