# Generated by Django 5.2.16 on 2026-08-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_alter_evenementagenda_chambre_and_more'),
        ('authentication', '0010_journalconnexion'),
        ('dossier', '0008_chambre_tribunal_typetribunal_alter_dossier_chambre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='type_tribunal',
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
        migrations.DeleteModel(
            name='Tribunal',
        ),
        migrations.DeleteModel(
            name='TypeTribunal',
        ),
    ]
