# Generated by Django 5.2.16 on 2026-07-26 18:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0011_alter_partieprenante_dossier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: AQILAS SMS, Orange BF', max_length=100, unique=True)),
                ('sender_id', models.CharField(default='CABINET', help_text="Nom de l'expéditeur affiché (ex: AQILAS)", max_length=11)),
                ('base_url', models.URLField(help_text='Ex: https://api.aqilas.com/v1')),
                ('api_key', models.CharField(help_text="Clé d'API ou Token d'authentification", max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Définir comme fournisseur par défaut')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur SMS API',
                'verbose_name_plural': 'Fournisseurs SMS API',
                'db_table': 'sms_providers',
            },
        ),
        migrations.CreateModel(
            name='SMSGroupEnvoi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('bulk_id', models.CharField(blank=True, db_index=True, help_text="ID retourné par l'API SMS", max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Coût total en XOF', max_digits=10, null=True)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé au Provider'), ('PARTIAL', 'Partiellement Livré'), ('DELIVERED', 'Tous Livrés'), ('FAILED', 'Échec Envoi')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evenement_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_sms', to='agenda.evenementagenda')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois', to='notifications.providersms')),
            ],
            options={
                'db_table': 'sms_group_envois',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSDetailDestinataire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sms_provider_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('telephone', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', "En cours d'acheminement"), ('DELIVERY_SUCCESS', 'Reçu par le destinataire'), ('DELIVERY_FAILED', 'Échec de livraison'), ('EXPIRED', 'Expiré')], db_index=True, default='PENDING', max_length=30)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('group_envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='notifications.smsgroupenvoi')),
            ],
            options={
                'db_table': 'sms_detail_destinataires',
            },
        ),
    ]
