# Generated by Django 5.2.16 on 2026-07-26 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_partieprenante_dossier'),
        ('dossier', '0007_remove_dossier_juridiction'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdetaildestinataire',
            name='partie_prenante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.partieprenante'),
        ),
        migrations.AddField(
            model_name='smsdetaildestinataire',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsgroupenvoi',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_sms', to='dossier.dossier'),
        ),
    ]
