# Generated by Django 5.2.16 on 2026-07-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_smsdetaildestinataire_partie_prenante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdetaildestinataire',
            name='destinataire',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsdetaildestinataire',
            name='expediteur',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
