# Generated by Django 5.2.16 on 2026-07-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_smsdetaildestinataire_destinataire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsdetaildestinataire',
            old_name='destinataire',
            new_name='destinataire_nom',
        ),
        migrations.AddField(
            model_name='smsdetaildestinataire',
            name='destinataire_role',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
