# Generated by Django 5.2.16 on 2026-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_destinataire_smsdetaildestinataire_destinataire_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersms',
            name='sender_id',
            field=models.CharField(help_text="Nom de l'expéditeur affiché (ex: AQILAS)", max_length=11),
        ),
    ]
